# Generated by Django 3.0.8 on 2020-07-11 13:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200711_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='base_price',
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.Product')),
            ],
            options={
                'ordering': ['min_amount'],
            },
        ),
    ]
