# Generated by Django 3.0.8 on 2020-07-11 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='bank_id',
            field=models.CharField(blank=True, max_length=24, null=True, unique=True),
        ),
    ]
